In [2]:
import pandas as pd

In [4]:
url = "https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv"
    
df = pd.read_csv(url)
df

,Customer ID,Gender,Age,Salary,Product ID,Price,Purchased
0,1,Female,49,61000,P01,2000,1
1,2,Male,36,30000,P02,2000,1
2,3,Female,26,81000,P02,3500,1
3,4,Female,32,74000,P01,7000,0
4,5,Female,42,56000,P01,5000,0
...,...,...,...,...,...,...,...
995,996,Male,21,73000,P02,5000,1
996,997,Male,62,54000,P01,5000,0
997,998,Female,41,20000,P03,2000,0
998,999,Male,22,29000,P03,5000,0


In [7]:
df.count()
len(df)

1000

In [8]:
# Converting categorical values to numerical using One hot encoding
gender_encoded = pd.get_dummies(df['Gender'])

In [9]:
gender_encoded

,Female,Male
0,1,0
1,0,1
2,1,0
3,1,0
4,1,0
...,...,...
995,0,1
996,0,1
997,1,0
998,0,1


In [11]:
# Reduce the variable (redundancy) to avoid overfeeding into the ML model, this 1 column containing 0, 1 includes both F and M in a single row
gender_encoded = pd.get_dummies(df['Gender'], drop_first=True)

In [17]:
# Concat the value into original df
df = pd.concat([df, gender_encoded], axis=1)

In [18]:
# Select relevant features for ML model and cast in numpy arrays
import numpy as np


In [20]:
# Assigning variable x and y
x = df[['Male','Age','Salary','Price']].to_numpy()
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]], dtype=int64)

In [21]:
y = df['Purchased'].to_numpy()
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [22]:
#Seperate the dataset into training set and test set to train and evaluate the ML model
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [24]:
x_train

array([[    1,    26, 28000,  5000],
       [    1,    54, 21000,  7000],
       [    0,    42, 22000,  5000],
       ...,
       [    0,    59, 91000,  2000],
       [    0,    31, 82000,  2000],
       [    0,    20, 34000,  5000]], dtype=int64)

In [25]:
# Scaling features
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [31]:
#Building ML model with KNN algorithm
from sklearn.neighbors import KNeighborsClassifier

k = 5
knn = KNeighborsClassifier(n_neighbors=k)

In [32]:
# Training the knn model with training data split earlier
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [33]:
# Testing the model to do predictions
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0], dtype=int64)

In [35]:
#Compare the predictions with the actual test data using accuracy score method from scikitlearn libraby
from sklearn.metrics import accuracy_score

In [36]:
# Accuracy comparison results projected in %
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.765

In [39]:
# Testing the model into new dataset of 10 new customers
df2 = pd.read_csv('https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/new_customers.csv')
df2

,Gender,Age,Salary,Product ID,Price
0,Male,24,38652,3,4446
1,Female,47,64727,1,5188
2,Male,46,54648,1,6193
3,Male,31,20018,3,4779
4,Male,58,77731,2,6855
5,Male,28,55478,1,6153
6,Female,48,54211,2,7588
7,Male,31,60076,3,5238
8,Female,42,29290,1,5418
9,Male,50,21445,1,5598


In [42]:
# Peforming One Hot Encoding and all neccesary steps to standardise the data format as our 1st df to be able to be fitted in ML
gender_encoded_2 = pd.get_dummies(df2['Gender'], drop_first=True)
gender_encoded_2

,Male
0,1
1,0
2,1
3,1
4,1
5,1
6,0
7,1
8,0
9,1


In [43]:
df2 = pd.concat([df2, gender_encoded_2], axis=1)
df2

,Gender,Age,Salary,Product ID,Price,Male
0,Male,24,38652,3,4446,1
1,Female,47,64727,1,5188,0
2,Male,46,54648,1,6193,1
3,Male,31,20018,3,4779,1
4,Male,58,77731,2,6855,1
5,Male,28,55478,1,6153,1
6,Female,48,54211,2,7588,0
7,Male,31,60076,3,5238,1
8,Female,42,29290,1,5418,0
9,Male,50,21445,1,5598,1


In [44]:
# Assigning x2, y2 variables
x2 = df2[['Male','Age','Salary','Price']].to_numpy()
x2

array([[    1,    24, 38652,  4446],
       [    0,    47, 64727,  5188],
       [    1,    46, 54648,  6193],
       [    1,    31, 20018,  4779],
       [    1,    58, 77731,  6855],
       [    1,    28, 55478,  6153],
       [    0,    48, 54211,  7588],
       [    1,    31, 60076,  5238],
       [    0,    42, 29290,  5418],
       [    1,    50, 21445,  5598]], dtype=int64)

In [46]:
x2_scale = scaler.fit_transform(x2)
x2_scale

array([[ 0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [-1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [ 0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [ 0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [ 0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 0.65465367, -1.17253359,  0.42748189,  0.44684845],
       [-1.52752523,  0.70352015,  0.35848928,  2.02079916],
       [ 0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-1.52752523,  0.14070403, -0.99854681, -0.35932143],
       [ 0.65465367,  0.89112553, -1.42573465, -0.16189207]])

In [47]:
y2_pred = knn.predict(x2_scale)
y2_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [48]:
# Add the prediction table to the df
df2['will_purchase'] = y2_pred
df2

,Gender,Age,Salary,Product ID,Price,Male,will_purchase
0,Male,24,38652,3,4446,1,0
1,Female,47,64727,1,5188,0,1
2,Male,46,54648,1,6193,1,1
3,Male,31,20018,3,4779,1,0
4,Male,58,77731,2,6855,1,0
5,Male,28,55478,1,6153,1,1
6,Female,48,54211,2,7588,0,0
7,Male,31,60076,3,5238,1,0
8,Female,42,29290,1,5418,0,0
9,Male,50,21445,1,5598,1,0
